name: fooddelivery
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.4.0
  provider: ^6.0.5
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  intl_phone_field: ^3.1.0
  otp_text_field: ^1.1.3
  iconly: ^1.0.1
  m_toast: ^0.2.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/


